### ISSUE TITLE
Component stopped working after updating to new version. Backword compatibility probably

### ISSUE THREAD

**Issue by Kinnza** [Lapple/react-input-datalist#4]
Im guessing it doesnt work because you changed it to work with react 0.14 and we are still in react 0.13...

**Comment by Lapple** [comment]
My bad, will fix this by deprecating 2.1.0, releasing 2.2.0 for React 0.13 and 3.0.0 for React 0.14.

**Comment by Lapple** [comment]
Done, but I messed up a little bit, so
- 2.3.0 can be used with React 0.13
- 3.0.0 can be used with React 0.14

Sorry for inconvenience, please see if you have any issues with these versions.
