### ISSUE TITLE
Why is JSX not transpiled?

### ISSUE THREAD

**Issue by samueleaton** [Lapple/react-input-datalist#5]
This lib assumes that I am going to use a module bundler, but I am building an app in Electron so I have Node in the client so I don't need webpack or anything. This means that my node_modules are not going to run through my transpiler (and they shouldn't have to).

My own code is being transpiled with babel, but it doesn't really make sense that I should have to transpile stuff in node_modules. 

Thanks!

**Comment by Lapple** [comment]
Fixed, now written in plain JS, released as v4.0.0. Please have a look.
